name: "Mediflower Visitor Management"
version: "1.0.0"
slug: "visitors_addon"
description: "Medical facility visitor sign-in management system with photo capture and digital signatures"
url: "https://www.mediflower.com"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 8420
panel_icon: mdi:clipboard-account-outline
init: false
startup: application

schema:
  admin_password: password?

map:
  - type: addon_config
    read_only: False
    path: /visitors_config
